Repository stolostron/grc-ui-api, pull requests merged in 2021-07, with the labels that each got.

#143 backport issue 13595 to 2.2
  .eslintrc.js
  package-lock.json
  src/v1/connectors/kube.js
  src/v1/models/generic.js
Labels: dco-signoff: yes, lgtm

#145 revert changes to the package file
  package-lock.json
Labels: dco-signoff: yes

#147 remove-ansible-grc-ui-api
  package-lock.json
  package.json
  src/v1/mocks/Ansible.js
  src/v1/models/ansible.js
  src/v1/schema/__snapshots__/ansible.test.js.snap
  src/v1/schema/ansible.test.js
Labels: approved, dco-signoff: yes, lgtm

#146 my first grc-ui-api fix for ansible secret listing
  src/v1/mocks/Ansible.js
  src/v1/models/ansible.js
  src/v1/schema/__snapshots__/ansible.test.js.snap
  src/v1/schema/ansible.test.js
Labels: approved, dco-signoff: yes, lgtm

#148 Update ansible endpoints
  src/v1/models/ansible.js
  src/v1/schema/query.js
Labels: approved, dco-signoff: yes, lgtm

#150 refresh the build by updating the date in the README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm

#152 Fix vulnerabilities by new image
  Dockerfile
  README.md
Labels: approved, dco-signoff: yes, lgtm

#154 Update OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm
