Repository stolostron/grc-ui-api, pull requests merged in 2022-01, with the labels that each got.

#174 [release-2.2] Update GH org to stolostron
  Makefile
  README.md
  package-lock.json
  package.json
Labels: lgtm

#175 [release-2.2] Update object-path and npm audit fix
  package-lock.json
  package.json
Labels: lgtm, dco-signoff: yes

#176 Update OWNERS
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#180 Switch to GH org stolostron
  Dockerfile
  Makefile
  README.md
  package-lock.json
  package.json
  src/v1/index.js
  src/v1/mocks/SourceLists.js
  src/v1/schema/__snapshots__/compliance.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#179 [release-2.4] Switch to GH org stolostron
  Dockerfile
  Makefile
  README.md
  package-lock.json
  package.json
  src/v1/index.js
  src/v1/mocks/SourceLists.js
  src/v1/schema/__snapshots__/compliance.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#178 [release-2.3] Switch to GH org stolostron
  Dockerfile
  Makefile
  README.md
  package-lock.json
  package.json
  src/v1/index.js
Labels: lgtm, approved, dco-signoff: yes

#181 [release-2.2] Push a `latest-2.2` tag
  .travis.yml
Labels: lgtm, approved, dco-signoff: yes
